routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function(){
// 	return view('auth.login');
// })->name('entrar');

Auth::routes(['register' => false, 'password.reset' => false, 'password.update' => false, 'password.email' => false]);
Route::get('/', 'HomeController@index')->name('m3');

Route::group(['prefix' => 'm3' ,'as' => 'm3.','middleware' => 'auth'], function () {

	Route::resource('usuarios', 'm3\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'm3\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'm3\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'm3\ProfileController@password']);

	Route::group(['prefix' => 'produtos' ,'as' => 'produtos.'], function () {

		Route::resource('categoria' , 'm3\CategoryProductsController',['except' => ['create','edit','update']]);
		Route::resource('lista' , 'm3\ProductsController');
		Route::resource('conteudo' , 'm3\ContentProductsController',['except' => ['show']]);

	});

	Route::group(['prefix' => 'paginas' ,'as' => 'paginas.'], function () {

		Route::resource('lista' , 'm3\PagesController',['except' => ['show']]);
		Route::resource('conteudo' , 'm3\ContentPagesController',['except' => ['show']]);
		Route::resource('categorias' , 'm3\CategoryPagesController',['except' => ['show']]);

	});
	
	Route::resource('slides' , 'm3\SlidesController',['except' => ['show']]);
	Route::resource('onde-estamos' , 'm3\MapsController',['except' => ['show']]);
	Route::resource('postagens' , 'm3\PostsController',['except' => ['show']]);
	Route::resource('configuracoes' , 'm3\SettingsController',['except' => ['show']]);
	Route::resource('galeria' , 'm3\GallerysController',['except' => ['index']]);
	Route::resource('contatos' , 'm3\ContactsController',['except' => ['create']]);
	Route::resource('newslleters' , 'm3\NewslletersController',['except' => ['create','update','edit','store']]);
	Route::resource('representantes' , 'm3\RepresentativesController',['except' => ['create','edit','store']]);

});

app/Http/Controllers/m3/BlogsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\Blogs;
use App\Http\Model\Files;

class BlogsController extends Controller
{
    
    public function index()
    {
        return view('m3.blogs.index');
    }

    
    public function create()
    {
        return view('m3.blogs.create');
    }

    
    public function store(Request $request)
    {
        $files = new Files;
        $files->upload($file, $request->image);

        $blogs = new Blogs;
        $blogs->setData($blogs, $request->all());
        $blogs->files_id = $files->id;

        try{
            $blogs->save();
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao cadastrar blog. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.blog.index')->with('success','Blog cadastrado com sucesso!');
    }

    
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        return view('m3.blogs.edit', ['blog' => Blogs::find($id)]);
    }

  
    public function update(Request $request, $id)
    {
        $blog = blog::find($id);
        $blog->setData($blog, $request->all());

        if(!$request->image):

            $files = new Files;
            $files->upload($file, $request->image);
            $blog->files_id = $files_id;

        endif;

        try{
            $blogs->save();
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao atualizar blog. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.blog.index')->with('success','Blog atualizado com sucesso!');
    }

  
    public function destroy($id)
    {
        $blog = blog::find($id);

        try{
            $blog->delete();
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao apagar blog. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.blog.index')->with('success','Blog apagado com sucesso!');
    }
}

app/Http/Controllers/m3/CategoryPagesController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\CategoryPages;

class CategoryPagesController extends Controller
{
    
    public function index()
    {
        return view('m3.pages.category.index', ['categorys'=> CategoryPages::paginate(15)]);
    }

    
    public function create()
    {
        return view('m3.pages.category.create');
    }

    
    public function store(Request $request)
    {
        $category = new CategoryPages();
        $category->setData($category,$request->all());

        try{
           $category->save(); 
        }catch(\Exception $e){
            return redirect()->back()->with('error','Error ao cadastrar categoria. Por favor entrar em contato com o suporte!');
        }

        return redirect()->route('m3.paginas.categorias.index')->with('success', 'Categoria cadastrado com sucesso!');
    }

    
    public function show($id)
    {
        //
    }

  
    public function edit($id)
    {
        return view('m3.pages.category.edit', ['category' => CategoryPages::find($id)]);
    }

  
    public function update(Request $request, $id)
    {
        $category = CategoryPages::find($id);
        $category->setData($category,$request->all());

        try{
           $category->save(); 
        }catch(\Exception $e){
            return redirect()->back()->with('error','Error ao cadastrar categoria. Por favor entrar em contato com o suporte!');
        }

        return redirect()->route('m3.paginas.categorias.index')->with('success', 'Categoria atualizado com sucesso!');
    }

    
    public function destroy($id)
    {
        // $category = CategoryPages::find($id);

        // try{
        //    $category->delete();
        // }catch(\Exception $e){
            // return redirect()->back()->with('error','Entre em contato com o suporte para solicitar a exclusão!');
        // }

        return redirect()->route('m3.categoria-de-paginas.index')->with('Error', 'Entre em contato com o suporte para solicitar a exclusão!');

    }
}

app/Http/Controllers/m3/CategoryProductsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\CategoryProducts;
use App\Http\Model\Pages;

class CategoryProductsController extends Controller
{
    
    public function index()
    {
        return view('m3.products.category',['categorys' => CategoryProducts::paginate(15), 'pages' => Pages::orderBy('title', 'asc')->get()]);
    }

 
    public function create()
    {
        //
    }

   
    public function store(Request $request)
    {
        $category = new CategoryProducts;
        $category->setData($category, $request->all());

        try{
            $category->save();
        }catch(\Exception $e){
            return redirect()->back()->with('error', 'Erro ao cadastrar categoria. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.produtos.categoria.index')->with('success', 'Categoria cadastrado com sucesso!');
    }

  
    public function show($id)
    {
        $category = CategoryProducts::where('pages_id', $id)->get();
        return response()->json($category);
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }

  
    public function destroy($id)
    {
        $category = CategoryProducts::find($id);
        try{
            $category->delete();
        }catch(\Exception $e){
            return redirect()->back()->with('error', 'Erro ao apagar categoria. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.produtos.categoria.index')->with('success', 'Categoria apagado com sucesso!');
    }
}

app/Http/Controllers/m3/ContactsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\Contacts;

class ContactsController extends Controller
{
    
    public function index()
    {
        return view('m3.contacts.index',['contacts' => Contacts::paginate(15)]);
    }

    
    public function create()
    {
        //
    }

   
    public function store(Request $request)
    {
        //
    }

    
    public function show($id)
    {
        $contact = Contacts::find($id);
        $contact->read = 1;
        $contact->save();

        return view('m3.contacts.show', compact('contact'));
    }

    
    public function edit($id)
    {
        //
    }

    
    public function update(Request $request, $id)
    {
        //
    }

   
    public function destroy($id)
    {
        $contact = Contacts::find($id);
        $contact->delete();

        return redirect()->route('m3.contatos.index')->with('success','Contato apagado com sucesso!');
    }
}

app/Http/Controllers/m3/ContentProductsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\ContentProducts;
use App\Http\Model\Products;

class ContentProductsController extends Controller
{
  
    public function index()
    {
        return view('m3.products.content.index',['content' => ContentProducts::paginate(15)]);
    }

    
    public function create()
    {
        return view('m3.products.content.create',['product' => Products::find(request()->id)]);
    }

   
    public function store(Request $request)
    {
        $contents = new ContentProducts;
        $contents->setData($contents, $request->all());

        try{
            $contents->save();
        }catch(\Exception $e){
            return redirect()->with('error','Error ao cadastrar conteúdo. Por favor entrar em contato com suporte');
        }

        return redirect()->route('m3.produtos.lista.show', $request->products_id)->with('success','Conteúdo de Produto cadastrado com sucesso!');
    }

   
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        return view('m3.products.content.edit',['content' => ContentProducts::find($id)]);
    }

    
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $content = ContentProducts::find($id);
        $content->setData($content, $request->all());

        try{
            $content->save();
        }catch(\Exception $e){
            return redirect()->with('error','Error ao atualizar conteúdo. Por favor entrar em contato com suporte');
        }

        return redirect()->route('m3.produtos.lista.show', $request->products_id)->with('success','Conteúdo de Produto atualizado com sucesso!');
    }

  
    public function destroy($id)
    {
        $content = ContentProducts::find($id);

        try{
            $content->delete();
        }catch(\Exception $e){
            return redirect()->with('error','Error ao apagar conteúdo. Por favor entrar em contato com suporte');
        }

        return redirect()->back()->with('success','Conteúdo de Produto apagado com sucesso!');
    }
}

app/Http/Controllers/m3/GallerysController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\Posts;
use App\Http\Model\Files;
use App\Http\Model\Gallerys;

class GallerysController extends Controller
{
    
    public function index($id)
    {
        
    }

   
    public function create()
    {
        return view('m3.gallerys.create',['post' => Posts::find(request()->id)]);
    }

    
    public function store(Request $request)
    {
        $post = Posts::find($request->post);
        $file = new Files;

        if($post->gallerys_id == null){
            $gallery = new Gallerys;
            $gallery->save();
            $request['gallery'] = $gallery->id;

            $file->gallerys_id = $gallery->id;
            $post->gallerys_id = $gallery->id;
        }else{
            $file->gallerys_id = $post->gallerys_id;
        }
        
        $file->uploadFile($file, $request->all());

        try{
            $post->save();
        }catch(\Exception $e){
            return redirect()->back()->with('error', 'Erro ao cadastrar Arquivos. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.galeria.show', $post->id)->with('success', 'Arquivo cadastrado com sucesso!');

    }

    
    public function show($id)
    {
        $post = Posts::find($id);
        $files = Files::where('gallerys_id', $post->gallerys_id)->get();
        return view('m3.gallerys.index', compact('post', 'files'));
    }

    
    public function edit($id)
    {
        $file = Files::find($id);
        $post = Posts::where('gallerys_id', $file->gallery_id)->first();    

        return view('m3.gallerys.edit', compact('file', 'post'));
    }

  
    public function update(Request $request, $id)
    {
        $file = Files::find($id);
        $post = Posts::where('gallerys_id', $file->gallerys_id)->first();

        // dd($request->all());

        $file->name = $request->title;

        if($request->file){

            $gallery = new Gallerys;
            $gallery->save();

            $file = new Files;
            $file->gallerys_id = $gallery->id;
            $file->uploadFile($file, $request->all());
            
            $post->gallerys_id = $gallery->id;
        }else{
            $file->save();
        }
        
        try{
            $post->save();
        }catch(\Exception $e){
            return redirect()->back()->with('error', 'Erro ao atualizar Arquivos. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.galeria.show',$post->id)->with('success', 'Arquivo atualizado com sucesso!');
    }

    
    public function destroy($id)
    {
        $file = Files::find($id);

        try{
            $file->delete();
        }catch(\Exception $e){
            return redirect()->back()->with('error', 'Erro ao apagar Arquivos. Por favor entre em contato com o suporte!');
        }

        return redirect()->back()->with('success', 'Arquivo apagado com sucesso!');
    }
}

app/Http/Controllers/m3/MapsController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use App\Http\Model\Maps;
use Illuminate\Http\Request;

class MapsController extends Controller
{
    
    public function index()
    {
        return view('m3.maps.index', ['maps' => Maps::paginate(15)]);
    }

    
    public function create()
    {
        return view('m3.maps.create');
    }

  
    public function store(Request $request)
    {
        $maps = new Maps;
        try{
             $maps->create($request->all());
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao cadastrar Mapa. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.onde-estamos.index')->with('success','Mapa cadastrado com sucesso!');
    }

    
    public function show(Maps $maps)
    {
        //
    }

    
    public function edit($id)
    {
        return view('m3.maps.edit',['map' => Maps::find($id)]);
    }

    
    public function update(Request $request, $id)
    {
        $map = Maps::find($id);

        try{
            $map->update($request->all());

        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao atualizar Mapa. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.onde-estamos.index')->with('success','Mapa atualizado com sucesso!');
    }

    
    public function destroy($id)
    {
        $map = Maps::find($id);
        try{
            $map->delete($id);
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao apagar Mapa. Por favor entre em contato com o suporte!');
        }

        return redirect()->route('m3.onde-estamos.index')->with('success','Mapa apagado com sucesso!');
    }
}

app/Http/Controllers/m3/NewslletersController.php
<?php

namespace App\Http\Controllers\m3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Model\Contacts;

class NewslletersController extends Controller
{
    
    public function index()
    {
        return view('m3.contacts.newslleter',['contacts' => Contacts::where('type','newslleter')->paginate(15)]);
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        //
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        //
    }

    
    public function update(Request $request, $id)
    {
        //
    }

   
    public function destroy($id)
    {
        $contact = Contacts::find($id);

        try{
            $contact->delete();
        }catch(\Exception $e){
            return redirect()->back()->with('error','Erro ao apagar newslleter. Por favor entre em contato com o suporte.');
        }

        return redirect()->back()->with('succcess','Newslleter apagado com sucesso.');
    }
}

resources/views/m3/products/category.blade.php
@extends('m3.layouts.app', ['title' => __('Categoria de Produtos')])

@section('content')
    @include('m3.layouts.headers.header', [
        'title' => __('Categorias de Produtos'),
        'description' => __('Cadastre a categoria de produtos ligado a uma página brevemente cadastrada.'),
        'class' => 'col-lg-12'
    ])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Categoria de Páginas</h3>
                            </div>
                            <div class="col-4 text-right">
                                <button class="btn btn-success btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                                    Adicionar
                                </button>
                            </div>
                            <div class="col-12">
                                <div class="collapse pt-5" id="collapseExample">
                                    <form class="" method="post" action="{{ route('m3.produtos.categoria.store') }}">
                                        @csrf
                                        <div class="form-row">
                                            <div class="form-group col-12 col-md-6 col-lg-5 col-xl-6">
                                                <input type="text" class="form-control" id="inlineFormInputName2" name="title" placeholder="Categoria de produto">
                                            </div>
                                            <div class="form-group col-12 col-md-6 col-lg-5 col-xl-5">
                                                <select name="pages_id" class="form-control">
                                                    <option value="">Selecione</option>
                                                    @foreach ($pages as $item)
                                                        <option value="{{ $item->id }}">{{ $item->title }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group col-12 col-md-12 col-lg-2 col-xl-1">
                                                <button type="submit" class="btn btn-success mb-2 w-auto">Cadastrar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Paginas</th>
                                    <th scope="col">Produtos</th>
                                    <th scope="col">Slug</th>
                                    <th scope="col">Criado</th>
                                    <th scope="col">Atualizado</th>
                                    <th scope="col">Opções</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($categorys as $item)                                   
                             
                                <tr>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->pages->title }}</td>
                                    <td>{{ $item->products->count() }}</td>
                                    <td>{{ $item->slug }}</td>
                                    <td>{{ $item->created_at->format('d-m-Y') }}</td>
                                    <td>{{ $item->updated_at->format('d-m-Y') }}</td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" href="{{ route('m3.produtos.categoria.destroy', $item->id) }}"><i class="fas fa-edit"></i>Editar</a>
                                                {{ deleteButton(route('m3.produtos.categoria.destroy', $item->id)) }}
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $categorys->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        @include('m3.layouts.footers.auth')
    </div>
@endsection
@push('js')

@endpush

resources/views/m3/products/index.blade.php
@extends('m3.layouts.app', ['title' => __('Produtos')])

@section('content')
    @include('m3.layouts.headers.header', [
        'title' => __('Produtos'),
        'description' => __('This is your profile page. You can see the progress you\'ve made with your work and manage your projects or assigned tasks'),
        'class' => 'col-lg-7'
    ])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Páginas</h3>
                            </div>
                            <div class="col-4 text-right">
                                <div class="dropdown dropleft">
                                    <a class="btn btn-danger dropdown-toggle btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Adicionar
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a href="{{ route('m3.produtos.categoria.index') }}" class="dropdown-item"><i class="far fa-caret-square-right"></i>Categoria de Produto</a>
                                        <a href="{{ route('m3.produtos.lista.create') }}" class="dropdown-item"><i class="fas fa-plus-square"></i>Produto</a>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th></th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Categoria</th>
                                    <th scope="col">Página</th>
                                    <th scope="col">Slug</th>
                                    <th scope="col">Criado</th>
                                    <th scope="col">Atualizado</th>
                                    <th scope="col">Opções</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $item)                                   
                             
                                <tr>
                                    <td><img src="{{ Storage::url($item->files->name) }}" width="100" height="50" alt="{{ $item->title }}"></td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->category_products->title }}</td>
                                    <td>{{ $item->pages->title }}</td>
                                    <td>{{ $item->slug }}</td>
                                    <td>{{ $item->created_at->format('d-m-Y') }}</td>
                                    <td>{{ $item->updated_at->format('d-m-Y') }}</td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" href="{{ route('m3.produtos.lista.edit', $item) }}"><i class="fas fa-edit"></i>Editar</a>
                                                <a class="dropdown-item" href="{{ route('m3.produtos.lista.show', $item) }}"><i class="fas fa-file-contract"></i>Conteúdo</a>
                                                {{ deleteButton(route('m3.produtos.lista.destroy', $item->id)) }}
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $products->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        @include('m3.layouts.footers.auth')
    </div>
@endsection